FROM rocm/pytorch:rocm7.2.2_ubuntu24.04_py3.12_pytorch_release_2.10.0

WORKDIR /workspace

COPY requirements/training-rocm.txt requirements/
COPY requirements/base.txt requirements/

RUN pip install -r requirements/training-rocm.txt

CMD ["/bin/bash"]