FROM python:3.12-slim

WORKDIR /workspace

RUN apt-get update && apt-get install -y \
    gcc g++ git \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip

COPY requirements/analysis-cpu.txt requirements/
COPY requirements/base.txt requirements/

RUN pip install -r requirements/analysis-cpu.txt

CMD ["/bin/bash"]
